volumes:
  db-data:

services:
  db:
    container_name: pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}"]
        interval: 30s
        timeout: 5s
        retries: 5
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
